// <auto-generated />
using System;
using IBMG.SCS.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IBMG.SCS.Infrastructure.Entities
{
    [DbContext(typeof(PortalDBContext))]
    [Migration("20260122131211_AddAircraft")]
    partial class AddAircraft
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.AircraftInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AircraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRowDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TailNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariantType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("YearOfManufacture")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AircraftInfo");
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.AuditLogs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreatedOnDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("CreatedOnTime")
                        .HasColumnType("time");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.BranchKerridgeMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KerridgeInstance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BranchKerridgeMaps");
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.DashboardItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TemplateType")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("dashboard", (string)null);
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.DashboardWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsRowDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("RowLayoutType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RowOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("WidgetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.HasIndex("WidgetId");

                    b.ToTable("dashboard_widgets", (string)null);
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.Emails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRowDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.JobRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRowDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("JobRoles");
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.Operatives", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRowDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobRole")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OperativeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OverrideDailyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("OverrideEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OverrideMonthlyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OverrideTnxLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OverrideWeeklyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TnxLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TradeCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WeeklyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Operatives");
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.TradeCards", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRowDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TradeCards");
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.Validation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ValidationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Validations");
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("widgets", (string)null);
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableAssignedResource", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceIdentifier")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "ResourceIdentifier");

                    b.ToTable((string)null);

                    b.ToView("vw_peardrop_authentication_assignedResource", (string)null);
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableAuthenticatorApp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("WhenEnrolled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WhenRevoked")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable((string)null);

                    b.ToView("vw_peardrop_authentication_authenticatorApp", (string)null);
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableAuthenticatorDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Aaguid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.Property<string>("CredType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("WhenEnrolled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WhenLastUsed")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable((string)null);

                    b.ToView("vw_peardrop_authentication_authenticatorDevice", (string)null);
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableExternalUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("Provider")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "ExternalReference", "Provider");

                    b.ToTable((string)null);

                    b.ToView("vw_peardrop_authentication_externalUser", (string)null);
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableMetaItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable((string)null);

                    b.ToView("vw_peardrop_authentication_metaItem", (string)null);
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryablePasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("WhenUsed")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable((string)null);

                    b.ToView("vw_peardrop_authentication_passwordHistory", (string)null);
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("vw_peardrop_authentication_profile", (string)null);
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeletable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserTypeFlags")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("vw_peardrop_authentication_role", (string)null);
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableRoleToGroupMapping", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DirectoryGroupRef")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "DirectoryGroupRef");

                    b.ToTable((string)null);

                    b.ToView("vw_peardrop_authentication_roleToDirectoryGroupMapping", (string)null);
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLockable")
                        .HasColumnType("bit");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserTypeFlags")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WhenDisabled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WhenLastAuthenticated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WhenLocked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WhenVerified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("vw_peardrop_authentication_user", (string)null);
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableUserPrincipalName", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiresVerification")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("WhenDisabled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WhenVerified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable((string)null);

                    b.ToView("vw_peardrop_authentication_userPrincipalName", (string)null);
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable((string)null);

                    b.ToView("vw_peardrop_authentication_userRole", (string)null);
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.DashboardWidget", b =>
                {
                    b.HasOne("IBMG.SCS.Infrastructure.Entities.DashboardItem", "Dashboard")
                        .WithMany("Widgets")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBMG.SCS.Infrastructure.Entities.Widget", "Widget")
                        .WithMany("DashboardWidgets")
                        .HasForeignKey("WidgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dashboard");

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableAssignedResource", b =>
                {
                    b.HasOne("PearDrop.Authentication.Queries.Entities.QueryableRole", "Role")
                        .WithMany("AssignedResources")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableAuthenticatorApp", b =>
                {
                    b.HasOne("PearDrop.Authentication.Queries.Entities.QueryableUser", "User")
                        .WithMany("AuthenticatorApps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableAuthenticatorDevice", b =>
                {
                    b.HasOne("PearDrop.Authentication.Queries.Entities.QueryableUser", "User")
                        .WithMany("AuthenticatorDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableExternalUser", b =>
                {
                    b.HasOne("PearDrop.Authentication.Queries.Entities.QueryableUser", "User")
                        .WithMany("ExternalUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableMetaItem", b =>
                {
                    b.HasOne("PearDrop.Authentication.Queries.Entities.QueryableUser", "User")
                        .WithMany("MetaItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryablePasswordHistory", b =>
                {
                    b.HasOne("PearDrop.Authentication.Queries.Entities.QueryableUser", "User")
                        .WithMany("PasswordHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableProfile", b =>
                {
                    b.HasOne("PearDrop.Authentication.Queries.Entities.QueryableUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("PearDrop.Authentication.Queries.Entities.QueryableProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableRoleToGroupMapping", b =>
                {
                    b.HasOne("PearDrop.Authentication.Queries.Entities.QueryableRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableUserPrincipalName", b =>
                {
                    b.HasOne("PearDrop.Authentication.Queries.Entities.QueryableUser", "User")
                        .WithMany("UserPrincipalNames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableUserRole", b =>
                {
                    b.HasOne("PearDrop.Authentication.Queries.Entities.QueryableRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PearDrop.Authentication.Queries.Entities.QueryableUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.DashboardItem", b =>
                {
                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("IBMG.SCS.Infrastructure.Entities.Widget", b =>
                {
                    b.Navigation("DashboardWidgets");
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableRole", b =>
                {
                    b.Navigation("AssignedResources");
                });

            modelBuilder.Entity("PearDrop.Authentication.Queries.Entities.QueryableUser", b =>
                {
                    b.Navigation("AuthenticatorApps");

                    b.Navigation("AuthenticatorDevices");

                    b.Navigation("ExternalUsers");

                    b.Navigation("MetaItems");

                    b.Navigation("PasswordHistories");

                    b.Navigation("Profile");

                    b.Navigation("UserPrincipalNames");
                });
#pragma warning restore 612, 618
        }
    }
}
